# Generated by Django 3.2 on 2021-04-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elecbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_id', models.CharField(max_length=100)),
                ('c_email', models.CharField(max_length=100)),
                ('c_date', models.CharField(max_length=100)),
                ('c_city', models.CharField(max_length=100)),
                ('c_address', models.CharField(max_length=100)),
                ('utility', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('bill', models.IntegerField()),
                ('copy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'table_elec',
            },
        ),
    ]
